package tests;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import java.util.List;

import org.testng.annotations.Test;

import pages.LoginPage;
import pages.RegistrationPage;

public class VerifyCountries extends BaseTest {

	LoginPage loginPage;
	RegistrationPage registrationPage;

	@Test(description = "Verify that all countries are present in the dropdown on the registration page", groups = {
			"regression" })
	public void verifyCountriesInDropdown() {

		// Initialize the LoginPage object
		loginPage = new LoginPage(driver);
		registrationPage = new RegistrationPage(driver);

		List<String> countries = List.of("ALBANIA", "ALGERIA", "AMERICAN SAMOA", "ANDORRA", "ANGOLA", "ANGUILLA",
				"ANTARCTICA", "ANTIGUA AND BARBUDA", "ARGENTINA", "ARMENIA", "ARUBA", "ASHMORE AND CARTIER ISLANDS",
				"AUSTRALIA", "AUSTRIA", "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BAKER ISLAND", "BANGLADESH", "BARBADOS",
				"BASSA DE INDIA", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BERMUDA", "BHUTAN", "BOLIVIA",
				"BOSNIA AND HERZEGOVINA", "BOTSWANA", "BOUVET ISLAND", "BRAZIL", "BRITISH INDIAN OCEAN TERRITORY",
				"BRITISH VIRGIN ISLANDS", "BRUNEI", "BULGARIA", "BURKINA FASO", "BURMA", "BURUNDI", "CAMBODIA",
				"CAMEROON", "CANADA", "CAPE VERDE", "CAYMAN ISLANDS", "CENTRAL AFRICAN REPUBLIC", "CHAD", "CHILE",
				"CHINA", "CHRISTMAS ISLAND", "CLIPPERTON ISLAND", "COCOS (KEELING) ISLANDS", "COLOMBIA", "COMOROS",
				"CONGO", "COOK ISLANDS", "CORAL SEA ISLANDS", "COSTA RICA", "COTE D'IVOIRE", "CROATIA", "CUBA",
				"CYPRUS", "CZECH REPUBLIC", "DENMARK", "DJIBOUTI", "DOMINICA", "DOMINICAN REPUBLIC", "ECUADOR", "EGYPT",
				"EL SALVADOR", "EQUATORIAL GUINEA", "ERITREA", "ESTONIA", "ETHIOPIA", "EUROPA ISLAND",
				"FALKLAND ISLANDS", "FAROE ISLANDS", "FIJI", "FINLAND", "FRANCE", "FRENCH GUIANA", "FRENCH POLYNESIA",
				"FRENCH SOUTHERN AND ANTARCTIC LANDS", "GABON", "GAMBIA, THE", "GAZA STRIP", "GEORGIA", "GERMANY",
				"GHANA", "GIBRALTAR", "GLORIOSO ISLANDS", "GREECE", "GREENLAND", "GRENADA", "GUADELOUPE", "GUAM",
				"GUATEMALA", "GUERNSEY", "GUINEA", "GUINEA-BISSAU", "GUYANA", "HAITI",
				"HEARD ISLAND AND MCDONALD ISLANDS", "HONDURAS", "HONG KONG", "HOWLAND ISLAND", "HUNGARY", "ICELAND",
				"INDIA", "INDONESIA", "IRAN", "IRAQ", "IRELAND", "ISRAEL", "ITALY", "JAMAICA", "JAN MAYEN", "JAPAN",
				"JARVIS ISLAND", "JERSEY", "JOHNSTON ATOLL", "JORDAN", "JUAN DE NOVA ISLAND", "KAZAKHSTAN", "KENYA",
				"KINGMAN REEF", "KIRIBATI", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KOREA, REPUBLIC OF", "KUWAIT",
				"KYRGYZSTAN", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIECHTENSTEIN", "LITHUANIA",
				"LUXEMBOURG", "MACAU", "MACEDONIA, FORMER REPUBLIC OF", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES",
				"MALI", "MALTA", "MAN, ISLE OF", "MARSHALL ISLANDS", "MARTINIQUE", "MAURITANIA", "MAURITIUS", "MAYOTTE",
				"MEXICO", "MICRONESIA", "MIDWAY ISLANDS", "MOLDOVA", "MONACO", "MONGOLIA", "MONTENEGRO", "MONTSERRAT",
				"MOROCCO", "MOZAMBIQUE", "NAMIBIA", "NAURU", "NAVASSA ISLAND", "NEPAL", "NETHERLANDS",
				"NETHERLANDS ANTILLES", "NEW CALEDONIA", "NEW ZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NIUE",
				"NO MANS LAND", "NORFOLK ISLAND", "NORTHERN MARIANA ISLANDS", "NORWAY", "OCEANS", "OMAN", "PAKISTAN",
				"PALMYRA ATOLL", "PANAMA", "PAPUA NEW GUINEA", "PARACEL ISLANDS", "PARAGUAY", "PERU", "PHILIPPINES",
				"PITCAIRN ISLANDS", "POLAND", "PORTUGAL", "PUERTO RICO", "QATAR", "REUNION", "ROMANIA", "RUSSIA",
				"RWANDA", "SAN MARINO", "SAO TOME AND PRINCIPE", "SAUDI ARABIA", "SENEGAL", "SERBIA", "SEYCHELLES",
				"SIERRA LEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA", "SOLOMON ISLANDS", "SOMALIA", "SOUTH AFRICA",
				"SOVIET UNION", "SPAIN", "SPRATLY ISLANDS", "SRI LANKA", "ST. HELENA", "ST. KITTS AND NEVIS",
				"ST. LUCIA", "ST. PIERRE AND MIQUELON", "ST. VINCENT AND THE GRENADINES", "SUDAN", "SURINAME",
				"SVALBARD", "SWAZILAND", "SWEDEN", "SWITZERLAND", "SYRIA", "TAIWAN", "TAJIKISTAN",
				"TANZANIA, UNITED REPUBLIC OF", "THAILAND", "TOGO", "TOKELAU", "TONGA", "TRINIDAD AND TOBAGO",
				"TROMELIN ISLAND", "TUNISIA", "TURKEY", "TURKMENISTAN", "TURKS AND CAICOS ISLANDS", "TUVALU", "UGANDA",
				"UKRAINE", "UNDERSEA FEATURES", "UNITED ARAB EMIRATES", "UNITED KINGDOM", "UNITED STATES", "URUGUAY",
				"UZBEKISTAN", "VANUATU", "VATICAN CITY", "VENEZUELA", "VIETNAM", "VIRGIN ISLANDS", "WAKE ISLAND",
				"WALLIS AND FUTUNA", "WEST BANK", "WESTERN SAHARA", "WESTERN SAMOA", "YEMEN", "YUGOSLAVIA", "ZAIRE",
				"ZAMBIA", "ZIMBABWE");

		// Click on the "REGISTER" link to navigate to the registration page
		loginPage.clickRegisterLink();
		utillities.FrameworkUtil.waitForElementToBeVisible(driver, registrationPage.getCountryDropdown());
		assertTrue(registrationPage.getCountryDropdown().isDisplayed(),
				"Country dropdown is not displayed on the registration page.");
		assertEquals(registrationPage.getAllOtionsFromCountryDropdown(), countries,
				"Country dropdown does not contain all expected countries.");

	}

}
